language: cpp
os:
    - linux
dist: 
    - xenial  
compiler:
    - gcc
before_install:
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial main restricted"
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial-updates main restricted"
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial universe"
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial-updates universe"
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial multiverse"
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial-updates multiverse"
    - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse"
    - sudo add-apt-repository -y "deb http://security.ubuntu.com/ubuntu xenial-security main restricted"
    - sudo add-apt-repository -y "deb http://security.ubuntu.com/ubuntu xenial-security universe"
    - sudo add-apt-repository -y "deb http://security.ubuntu.com/ubuntu xenial-security multiverse"
    - sudo apt update
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/fxcpy/cpp/lib
install:
    - cd JamesKBowler/fxcpy/fxcpy/cpp && mkdir build && cd JamesKBowler/fxcpy/fxcpy/cpp/build
    - cmake ..
    - sudo make install -j2
    - cd JamesKBowler/fxcpy
    - pip3 install . --no-cache-dir
