language: cpp
os: linux
dist: bionic
compiler: gcc
sudo: true

before install:
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic main restricted'
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic-updates main restricted'
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic universe'
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic-updates universe'
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse'
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic-updates multiverse'
    - sudo add-apt-repository -y 'deb http://gb.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse'
    - sudo add-apt-repository -y 'deb http://security.ubuntu.com/ubuntu bionic-security main restricted'
    - sudo add-apt-repository -y 'deb http://security.ubuntu.com/ubuntu bionic-security universe'
    - sudo add-apt-repository -y 'deb http://security.ubuntu.com/ubuntu bionic-security multiverse'

install:
    - sudo apt update
    
script:
    - chmod +x install_script.sh && sudo ./install_script.sh
    
# blocklist
branches:
  except:
  - dev

# safelist
branches:
  only:
  - master
  - stable
  
#after_success:
#  - coveralls
