language: cpp
os:
  - linux
compiler:
  - gcc
before_install:
  - sudo apt update
  - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial universe"
  - sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu/ xenial-updates main restricted"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/fxcpy/cpp/lib
install:
  - chmod +x install_script.sh && sudo ./install_script.sh > /dev/null
