language: cpp
os:
  - linux
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/fxcpy/cpp/lib
install:
  - chmod +x install_script.sh && sudo ./install_script.sh
